Started by user [8mha:////4BMGkg3j4zNuSbeulW5IjFjaD1nGIqcqfegRoL5kSA3FAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0mFatih
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/docker-job
[docker-job] $ ansible-playbook /var/jenkins_home/ansible/docker.yml -i /var/jenkins_home/ansible/hosts -f 5 -e "MSG='Guys you are amazing'"
/usr/local/lib/python3.5/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.exceptions import InvalidSignature

PLAY [test1] *******************************************************************

TASK [Gathering Facts] *********************************************************
ok: [test1]

TASK [debug] *******************************************************************
ok: [test1] => {
    "msg": "Guys you are amazing"
}

PLAY RECAP *********************************************************************
test1                      : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Finished: SUCCESS
